apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
    spec:
      containers:
      - image: wonderwow/frontend
        name: frontend
        env:
          - name: "BACKEND_URL"
            value: "http://service-backend:5001"
        ports:
        - containerPort: 5000

