apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-frontend
  name: service-frontend
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 30080
  selector:
    app: frontend
  type: NodePort