apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-backend
  name: service-backend
spec:
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    app: backend
  type: ClusterIP
