apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
spec:
  destination:
    name: ''
    namespace: frontend
    server: 'https://kubernetes.default.svc'
  source:
    path: frontend
    repoURL: 'https://github.com/1wonderwonder/ArgoCD'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
